name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore ./SistemaLlavesWebAPI/SistemaLlavesWebAPI.sln
  # Restaura las dependencias para todos los proyectos en la solución

    - name: Build
      run: dotnet build ./SistemaLlavesWebAPI.sln --no-restore  # Construye todos los proyectos de la solución

    - name: Test
      run: dotnet test ./SistemaLlavesWebAPI.sln --no-build --verbosity normal 
