# Workflow para compilar y desplegar una aplicación ASP.NET Core en Azure

name: Build and deploy ASP.Net Core app to Azure Web App - SistemaLlavesWebApi

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout código fuente
        uses: actions/checkout@v4

      - name: Configurar .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # Especifica la versión estable

      - name: Restaurar paquetes
        run: dotnet restore ./SistemaLlavesWebApi/SistemaLlavesWebApi.sln

      - name: Compilar con dotnet
        run: dotnet build ./SistemaLlavesWebApi/SistemaLlavesWebApi.sln --configuration Release --no-restore

      - name: Publicar la aplicación
        run: dotnet publish ./SistemaLlavesWebApi/SistemaLlavesWebApi.sln --configuration Release --output ${{ github.workspace }}/publish

      - name: Subir artefacto para el job de despliegue
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ github.workspace }}/publish

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Descargar artefacto del job de compilación
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ${{ github.workspace }}/publish

      - name: Desplegar en Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'SistemaLlavesWebApi'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_F2D285300F02431091D1CC373974024E }}
          package: ${{ github.workspace }}/publish

